var wms_layers = [];


        var lyr_BDOrthoIGN_0 = new ol.layer.Tile({
            'title': 'BDOrtho IGN',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' &nbsp &middot; <a href="https://openstreetmap.fr/bdortho">BDOrtho IGN</a>',
                url: 'https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/{z}/{x}/{y}.jpg'
            })
        });
var format_CommunautdeCommunesBrayEawy_1 = new ol.format.GeoJSON();
var features_CommunautdeCommunesBrayEawy_1 = format_CommunautdeCommunesBrayEawy_1.readFeatures(json_CommunautdeCommunesBrayEawy_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CommunautdeCommunesBrayEawy_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CommunautdeCommunesBrayEawy_1.addFeatures(features_CommunautdeCommunesBrayEawy_1);
var lyr_CommunautdeCommunesBrayEawy_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CommunautdeCommunesBrayEawy_1, 
                style: style_CommunautdeCommunesBrayEawy_1,
                popuplayertitle: 'Communauté de Communes Bray-Eawy',
                interactive: true,
                title: '<img src="styles/legend/CommunautdeCommunesBrayEawy_1.png" /> Communauté de Communes Bray-Eawy'
            });
var format_CommunautdeCommunesdeLondinires_2 = new ol.format.GeoJSON();
var features_CommunautdeCommunesdeLondinires_2 = format_CommunautdeCommunesdeLondinires_2.readFeatures(json_CommunautdeCommunesdeLondinires_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CommunautdeCommunesdeLondinires_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CommunautdeCommunesdeLondinires_2.addFeatures(features_CommunautdeCommunesdeLondinires_2);
var lyr_CommunautdeCommunesdeLondinires_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CommunautdeCommunesdeLondinires_2, 
                style: style_CommunautdeCommunesdeLondinires_2,
                popuplayertitle: 'Communauté de Communes de Londinières',
                interactive: true,
                title: '<img src="styles/legend/CommunautdeCommunesdeLondinires_2.png" /> Communauté de Communes de Londinières'
            });
var format_CommunautdeCommunesdes4Rivires_3 = new ol.format.GeoJSON();
var features_CommunautdeCommunesdes4Rivires_3 = format_CommunautdeCommunesdes4Rivires_3.readFeatures(json_CommunautdeCommunesdes4Rivires_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CommunautdeCommunesdes4Rivires_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_CommunautdeCommunesdes4Rivires_3.addFeatures(features_CommunautdeCommunesdes4Rivires_3);
var lyr_CommunautdeCommunesdes4Rivires_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_CommunautdeCommunesdes4Rivires_3, 
                style: style_CommunautdeCommunesdes4Rivires_3,
                popuplayertitle: 'Communauté de Communes des 4 Rivières',
                interactive: true,
                title: '<img src="styles/legend/CommunautdeCommunesdes4Rivires_3.png" /> Communauté de Communes des 4 Rivières'
            });
var format_PETRduPaysdeBray_4 = new ol.format.GeoJSON();
var features_PETRduPaysdeBray_4 = format_PETRduPaysdeBray_4.readFeatures(json_PETRduPaysdeBray_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_PETRduPaysdeBray_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_PETRduPaysdeBray_4.addFeatures(features_PETRduPaysdeBray_4);
var lyr_PETRduPaysdeBray_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_PETRduPaysdeBray_4, 
                style: style_PETRduPaysdeBray_4,
                popuplayertitle: 'PETR du Pays de Bray',
                interactive: false,
                title: '<img src="styles/legend/PETRduPaysdeBray_4.png" /> PETR du Pays de Bray'
            });
var format_Communes_5 = new ol.format.GeoJSON();
var features_Communes_5 = format_Communes_5.readFeatures(json_Communes_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Communes_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Communes_5.addFeatures(features_Communes_5);
var lyr_Communes_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Communes_5, 
                style: style_Communes_5,
                popuplayertitle: 'Communes',
                interactive: false,
                title: '<img src="styles/legend/Communes_5.png" /> Communes'
            });
var format_Boissonsetdrivs_6 = new ol.format.GeoJSON();
var features_Boissonsetdrivs_6 = format_Boissonsetdrivs_6.readFeatures(json_Boissonsetdrivs_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Boissonsetdrivs_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Boissonsetdrivs_6.addFeatures(features_Boissonsetdrivs_6);
var lyr_Boissonsetdrivs_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Boissonsetdrivs_6, 
                style: style_Boissonsetdrivs_6,
                popuplayertitle: 'Boissons et dérivés',
                interactive: true,
                title: '<img src="styles/legend/Boissonsetdrivs_6.png" /> Boissons et dérivés'
            });
var format_Produitsdivers_7 = new ol.format.GeoJSON();
var features_Produitsdivers_7 = format_Produitsdivers_7.readFeatures(json_Produitsdivers_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Produitsdivers_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Produitsdivers_7.addFeatures(features_Produitsdivers_7);
var lyr_Produitsdivers_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Produitsdivers_7, 
                style: style_Produitsdivers_7,
                popuplayertitle: 'Produits divers',
                interactive: true,
                title: '<img src="styles/legend/Produitsdivers_7.png" /> Produits divers'
            });
var format_Poissonsetescargots_8 = new ol.format.GeoJSON();
var features_Poissonsetescargots_8 = format_Poissonsetescargots_8.readFeatures(json_Poissonsetescargots_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Poissonsetescargots_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Poissonsetescargots_8.addFeatures(features_Poissonsetescargots_8);
var lyr_Poissonsetescargots_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Poissonsetescargots_8, 
                style: style_Poissonsetescargots_8,
                popuplayertitle: 'Poissons et escargots',
                interactive: true,
                title: '<img src="styles/legend/Poissonsetescargots_8.png" /> Poissons et escargots'
            });
var format_Produitslaitiers_9 = new ol.format.GeoJSON();
var features_Produitslaitiers_9 = format_Produitslaitiers_9.readFeatures(json_Produitslaitiers_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Produitslaitiers_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Produitslaitiers_9.addFeatures(features_Produitslaitiers_9);
var lyr_Produitslaitiers_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Produitslaitiers_9, 
                style: style_Produitslaitiers_9,
                popuplayertitle: 'Produits laitiers',
                interactive: true,
                title: '<img src="styles/legend/Produitslaitiers_9.png" /> Produits laitiers'
            });
var format_Viandesetufs_10 = new ol.format.GeoJSON();
var features_Viandesetufs_10 = format_Viandesetufs_10.readFeatures(json_Viandesetufs_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Viandesetufs_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Viandesetufs_10.addFeatures(features_Viandesetufs_10);
var lyr_Viandesetufs_10 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Viandesetufs_10, 
                style: style_Viandesetufs_10,
                popuplayertitle: 'Viandes et œufs',
                interactive: true,
                title: '<img src="styles/legend/Viandesetufs_10.png" /> Viandes et œufs'
            });
var format_Fruitslgumesetherbesaromatiques_11 = new ol.format.GeoJSON();
var features_Fruitslgumesetherbesaromatiques_11 = format_Fruitslgumesetherbesaromatiques_11.readFeatures(json_Fruitslgumesetherbesaromatiques_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Fruitslgumesetherbesaromatiques_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Fruitslgumesetherbesaromatiques_11.addFeatures(features_Fruitslgumesetherbesaromatiques_11);
var lyr_Fruitslgumesetherbesaromatiques_11 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Fruitslgumesetherbesaromatiques_11, 
                style: style_Fruitslgumesetherbesaromatiques_11,
                popuplayertitle: 'Fruits, légumes et herbes aromatiques',
                interactive: true,
                title: '<img src="styles/legend/Fruitslgumesetherbesaromatiques_11.png" /> Fruits, légumes et herbes aromatiques'
            });
var format_Multiproduit_12 = new ol.format.GeoJSON();
var features_Multiproduit_12 = format_Multiproduit_12.readFeatures(json_Multiproduit_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Multiproduit_12 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Multiproduit_12.addFeatures(features_Multiproduit_12);
var lyr_Multiproduit_12 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Multiproduit_12, 
                style: style_Multiproduit_12,
                popuplayertitle: 'Multiproduit',
                interactive: true,
                title: '<img src="styles/legend/Multiproduit_12.png" /> Multiproduit'
            });
var format_Marchs_13 = new ol.format.GeoJSON();
var features_Marchs_13 = format_Marchs_13.readFeatures(json_Marchs_13, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Marchs_13 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Marchs_13.addFeatures(features_Marchs_13);
var lyr_Marchs_13 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Marchs_13, 
                style: style_Marchs_13,
                popuplayertitle: 'Marchés',
                interactive: true,
                title: '<img src="styles/legend/Marchs_13.png" /> Marchés'
            });
var group_Producteursmarchslocaux = new ol.layer.Group({
                                layers: [lyr_Boissonsetdrivs_6,lyr_Produitsdivers_7,lyr_Poissonsetescargots_8,lyr_Produitslaitiers_9,lyr_Viandesetufs_10,lyr_Fruitslgumesetherbesaromatiques_11,lyr_Multiproduit_12,lyr_Marchs_13,],
                                fold: "open",
                                title: 'Producteurs & marchés locaux'});
var group_Limitesadministratives = new ol.layer.Group({
                                layers: [lyr_CommunautdeCommunesBrayEawy_1,lyr_CommunautdeCommunesdeLondinires_2,lyr_CommunautdeCommunesdes4Rivires_3,lyr_PETRduPaysdeBray_4,lyr_Communes_5,],
                                fold: "open",
                                title: 'Limites administratives'});

lyr_BDOrthoIGN_0.setVisible(true);lyr_CommunautdeCommunesBrayEawy_1.setVisible(false);lyr_CommunautdeCommunesdeLondinires_2.setVisible(false);lyr_CommunautdeCommunesdes4Rivires_3.setVisible(false);lyr_PETRduPaysdeBray_4.setVisible(true);lyr_Communes_5.setVisible(true);lyr_Boissonsetdrivs_6.setVisible(true);lyr_Produitsdivers_7.setVisible(true);lyr_Poissonsetescargots_8.setVisible(true);lyr_Produitslaitiers_9.setVisible(true);lyr_Viandesetufs_10.setVisible(true);lyr_Fruitslgumesetherbesaromatiques_11.setVisible(true);lyr_Multiproduit_12.setVisible(true);lyr_Marchs_13.setVisible(true);
var layersList = [lyr_BDOrthoIGN_0,group_Limitesadministratives,group_Producteursmarchslocaux];
lyr_CommunautdeCommunesBrayEawy_1.set('fieldAliases', {'ID': 'ID', 'CODE_SIREN': 'CODE_SIREN', 'NATURE': 'NATURE', 'NOM': 'NOM', 'DATE_CREAT': 'DATE_CREAT', 'DATE_MAJ': 'DATE_MAJ', 'DATE_APP': 'DATE_APP', 'DATE_CONF': 'DATE_CONF', 'ID_AUT_ADM': 'ID_AUT_ADM', });
lyr_CommunautdeCommunesdeLondinires_2.set('fieldAliases', {'CODE_SIREN': 'CODE_SIREN', 'NATURE': 'NATURE', 'NOM': 'NOM', 'DATE_CREAT': 'DATE_CREAT', 'DATE_MAJ': 'DATE_MAJ', 'DATE_APP': 'DATE_APP', 'DATE_CONF': 'DATE_CONF', 'ID_AUT_ADM': 'ID_AUT_ADM', });
lyr_CommunautdeCommunesdes4Rivires_3.set('fieldAliases', {'ID': 'ID', 'CODE_SIREN': 'CODE_SIREN', 'NATURE': 'NATURE', 'NOM': 'NOM', 'DATE_CREAT': 'DATE_CREAT', 'DATE_MAJ': 'DATE_MAJ', 'DATE_APP': 'DATE_APP', 'DATE_CONF': 'DATE_CONF', 'ID_AUT_ADM': 'ID_AUT_ADM', });
lyr_PETRduPaysdeBray_4.set('fieldAliases', {'ID': 'ID', 'CODE_SIREN': 'CODE_SIREN', 'NATURE': 'NATURE', 'NOM': 'NOM', 'DATE_CREAT': 'DATE_CREAT', 'DATE_MAJ': 'DATE_MAJ', 'DATE_APP': 'DATE_APP', 'DATE_CONF': 'DATE_CONF', 'ID_AUT_ADM': 'ID_AUT_ADM', 'layer': 'layer', 'path': 'path', });
lyr_Communes_5.set('fieldAliases', {'ID': 'ID', 'INSEE_COM': 'INSEE_COM', 'INSEE_ARR': 'INSEE_ARR', 'INSEE_COL': 'INSEE_COL', 'INSEE_DEP': 'INSEE_DEP', 'INSEE_REG': 'INSEE_REG', 'POPULATION': 'POPULATION', 'SURFACE_HA': 'SURFACE_HA', 'DATE_CREAT': 'DATE_CREAT', 'DATE_MAJ': 'DATE_MAJ', 'DATE_APP': 'DATE_APP', 'DATE_CONF': 'DATE_CONF', 'CODE_POST': 'CODE_POST', 'NOM': 'NOM', 'CL_ARROND': 'CL_ARROND', 'CL_COLLTER': 'CL_COLLTER', 'CL_DEPART': 'CL_DEPART', 'CL_REGION': 'CL_REGION', 'CAPITALE': 'CAPITALE', 'DATE_RCT': 'DATE_RCT', 'RECENSEUR': 'RECENSEUR', 'SIREN_EPCI': 'SIREN_EPCI', 'ID_CH_LIEU': 'ID_CH_LIEU', 'ID_AUT_ADM': 'ID_AUT_ADM', 'CODE_SIREN': 'CODE_SIREN', 'layer': 'layer', 'path': 'path', });
lyr_Boissonsetdrivs_6.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Produitsdivers_7.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Poissonsetescargots_8.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Produitslaitiers_9.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Viandesetufs_10.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Fruitslgumesetherbesaromatiques_11.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Multiproduit_12.set('fieldAliases', {'fid': 'fid', 'N° Carte': 'N° Carte', 'Nom de la structure :': 'Nom de la structure :', 'Commune où se situe le lieu de vente directe :': 'Commune où se situe le lieu de vente directe :', 'Code postal :': 'Code postal :', 'N° rue / nom de rue :': 'N° rue / nom de rue :', 'E-mail :': 'E-mail :', 'Numéro de téléphone :': 'Numéro de téléphone :', 'Site internet :': 'Site internet :', 'Page Facebook :': 'Page Facebook :', 'Horaires d\'accueil :': 'Horaires d\'accueil :', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :', 'Type de production :': 'Type de production :', 'Produits à la vente :': 'Produits à la vente :', 'Précisions': 'Précisions', 'AOP (Appellation d\'origine protégée)': 'AOP (Appellation d\'origine protégée)', 'AB (Agriculture Biologique)': 'AB (Agriculture Biologique)', 'IGP (Indication Géographique Protégée)': 'IGP (Indication Géographique Protégée)', 'Label rouge': 'Label rouge', 'STG (Spécialité Traditionnelle Garantie)': 'STG (Spécialité Traditionnelle Garantie)', 'HVE (Haute Valeur Environnementale)': 'HVE (Haute Valeur Environnementale)', 'Autres labels et précisions :': 'Autres labels et précisions :', 'Gp_prod': 'Gp_prod', 'longitude': 'longitude', 'latitude': 'latitude', 'result_score': 'result_score', 'result_score_next': 'result_score_next', 'result_label': 'result_label', 'result_type': 'result_type', 'result_id': 'result_id', 'result_housenumber': 'result_housenumber', 'result_name': 'result_name', 'result_street': 'result_street', 'result_postcode': 'result_postcode', 'result_city': 'result_city', 'result_context': 'result_context', 'result_citycode': 'result_citycode', 'result_oldcitycode': 'result_oldcitycode', 'result_oldcity': 'result_oldcity', 'result_district': 'result_district', 'result_status': 'result_status', });
lyr_Marchs_13.set('fieldAliases', {'fid': 'fid', 'Adresse': 'Adresse', 'Jours d\'ouverture': 'Jours d\'ouverture', 'Horaires': 'Horaires', });
lyr_CommunautdeCommunesBrayEawy_1.set('fieldImages', {'ID': 'TextEdit', 'CODE_SIREN': 'TextEdit', 'NATURE': 'TextEdit', 'NOM': 'TextEdit', 'DATE_CREAT': 'TextEdit', 'DATE_MAJ': 'TextEdit', 'DATE_APP': 'DateTime', 'DATE_CONF': 'DateTime', 'ID_AUT_ADM': 'TextEdit', });
lyr_CommunautdeCommunesdeLondinires_2.set('fieldImages', {'CODE_SIREN': 'TextEdit', 'NATURE': 'TextEdit', 'NOM': 'TextEdit', 'DATE_CREAT': 'TextEdit', 'DATE_MAJ': 'TextEdit', 'DATE_APP': 'DateTime', 'DATE_CONF': 'DateTime', 'ID_AUT_ADM': 'TextEdit', });
lyr_CommunautdeCommunesdes4Rivires_3.set('fieldImages', {'ID': 'TextEdit', 'CODE_SIREN': 'TextEdit', 'NATURE': 'TextEdit', 'NOM': 'TextEdit', 'DATE_CREAT': 'TextEdit', 'DATE_MAJ': 'TextEdit', 'DATE_APP': 'DateTime', 'DATE_CONF': 'DateTime', 'ID_AUT_ADM': 'TextEdit', });
lyr_PETRduPaysdeBray_4.set('fieldImages', {'ID': 'TextEdit', 'CODE_SIREN': 'TextEdit', 'NATURE': 'TextEdit', 'NOM': 'TextEdit', 'DATE_CREAT': 'TextEdit', 'DATE_MAJ': 'TextEdit', 'DATE_APP': 'DateTime', 'DATE_CONF': 'DateTime', 'ID_AUT_ADM': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', });
lyr_Communes_5.set('fieldImages', {'ID': 'TextEdit', 'INSEE_COM': 'TextEdit', 'INSEE_ARR': 'TextEdit', 'INSEE_COL': 'TextEdit', 'INSEE_DEP': 'TextEdit', 'INSEE_REG': 'TextEdit', 'POPULATION': 'Range', 'SURFACE_HA': 'Range', 'DATE_CREAT': 'TextEdit', 'DATE_MAJ': 'TextEdit', 'DATE_APP': 'DateTime', 'DATE_CONF': 'DateTime', 'CODE_POST': 'TextEdit', 'NOM': 'TextEdit', 'CL_ARROND': 'TextEdit', 'CL_COLLTER': 'TextEdit', 'CL_DEPART': 'TextEdit', 'CL_REGION': 'TextEdit', 'CAPITALE': 'TextEdit', 'DATE_RCT': 'DateTime', 'RECENSEUR': 'TextEdit', 'SIREN_EPCI': 'TextEdit', 'ID_CH_LIEU': 'TextEdit', 'ID_AUT_ADM': 'TextEdit', 'CODE_SIREN': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', });
lyr_Boissonsetdrivs_6.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Produitsdivers_7.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Poissonsetescargots_8.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Produitslaitiers_9.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Viandesetufs_10.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Fruitslgumesetherbesaromatiques_11.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Multiproduit_12.set('fieldImages', {'fid': 'TextEdit', 'N° Carte': 'Range', 'Nom de la structure :': 'TextEdit', 'Commune où se situe le lieu de vente directe :': 'TextEdit', 'Code postal :': 'Range', 'N° rue / nom de rue :': 'TextEdit', 'E-mail :': 'TextEdit', 'Numéro de téléphone :': 'TextEdit', 'Site internet :': 'TextEdit', 'Page Facebook :': 'TextEdit', 'Horaires d\'accueil :': 'TextEdit', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'TextEdit', 'Type de production :': 'TextEdit', 'Produits à la vente :': 'TextEdit', 'Précisions': 'TextEdit', 'AOP (Appellation d\'origine protégée)': 'TextEdit', 'AB (Agriculture Biologique)': 'TextEdit', 'IGP (Indication Géographique Protégée)': 'TextEdit', 'Label rouge': 'TextEdit', 'STG (Spécialité Traditionnelle Garantie)': 'TextEdit', 'HVE (Haute Valeur Environnementale)': 'TextEdit', 'Autres labels et précisions :': 'TextEdit', 'Gp_prod': 'TextEdit', 'longitude': 'TextEdit', 'latitude': 'TextEdit', 'result_score': 'TextEdit', 'result_score_next': 'TextEdit', 'result_label': 'TextEdit', 'result_type': 'TextEdit', 'result_id': 'TextEdit', 'result_housenumber': 'TextEdit', 'result_name': 'TextEdit', 'result_street': 'TextEdit', 'result_postcode': 'Range', 'result_city': 'TextEdit', 'result_context': 'TextEdit', 'result_citycode': 'Range', 'result_oldcitycode': 'Range', 'result_oldcity': 'TextEdit', 'result_district': 'TextEdit', 'result_status': 'TextEdit', });
lyr_Marchs_13.set('fieldImages', {'fid': 'TextEdit', 'Adresse': 'TextEdit', 'Jours d\'ouverture': 'TextEdit', 'Horaires': 'TextEdit', });
lyr_CommunautdeCommunesBrayEawy_1.set('fieldLabels', {'ID': 'hidden field', 'CODE_SIREN': 'hidden field', 'NATURE': 'hidden field', 'NOM': 'hidden field', 'DATE_CREAT': 'hidden field', 'DATE_MAJ': 'hidden field', 'DATE_APP': 'hidden field', 'DATE_CONF': 'hidden field', 'ID_AUT_ADM': 'hidden field', });
lyr_CommunautdeCommunesdeLondinires_2.set('fieldLabels', {'CODE_SIREN': 'hidden field', 'NATURE': 'hidden field', 'NOM': 'hidden field', 'DATE_CREAT': 'hidden field', 'DATE_MAJ': 'hidden field', 'DATE_APP': 'hidden field', 'DATE_CONF': 'hidden field', 'ID_AUT_ADM': 'hidden field', });
lyr_CommunautdeCommunesdes4Rivires_3.set('fieldLabels', {'ID': 'hidden field', 'CODE_SIREN': 'hidden field', 'NATURE': 'hidden field', 'NOM': 'hidden field', 'DATE_CREAT': 'hidden field', 'DATE_MAJ': 'hidden field', 'DATE_APP': 'hidden field', 'DATE_CONF': 'hidden field', 'ID_AUT_ADM': 'hidden field', });
lyr_PETRduPaysdeBray_4.set('fieldLabels', {'ID': 'hidden field', 'CODE_SIREN': 'hidden field', 'NATURE': 'hidden field', 'NOM': 'hidden field', 'DATE_CREAT': 'hidden field', 'DATE_MAJ': 'hidden field', 'DATE_APP': 'hidden field', 'DATE_CONF': 'hidden field', 'ID_AUT_ADM': 'hidden field', 'layer': 'hidden field', 'path': 'hidden field', });
lyr_Communes_5.set('fieldLabels', {'ID': 'hidden field', 'INSEE_COM': 'hidden field', 'INSEE_ARR': 'hidden field', 'INSEE_COL': 'hidden field', 'INSEE_DEP': 'hidden field', 'INSEE_REG': 'hidden field', 'POPULATION': 'hidden field', 'SURFACE_HA': 'hidden field', 'DATE_CREAT': 'hidden field', 'DATE_MAJ': 'hidden field', 'DATE_APP': 'hidden field', 'DATE_CONF': 'hidden field', 'CODE_POST': 'hidden field', 'NOM': 'hidden field', 'CL_ARROND': 'hidden field', 'CL_COLLTER': 'hidden field', 'CL_DEPART': 'hidden field', 'CL_REGION': 'hidden field', 'CAPITALE': 'hidden field', 'DATE_RCT': 'hidden field', 'RECENSEUR': 'hidden field', 'SIREN_EPCI': 'hidden field', 'ID_CH_LIEU': 'hidden field', 'ID_AUT_ADM': 'hidden field', 'CODE_SIREN': 'hidden field', 'layer': 'hidden field', 'path': 'hidden field', });
lyr_Boissonsetdrivs_6.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - always visible', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - always visible', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Produitsdivers_7.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Poissonsetescargots_8.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Produitslaitiers_9.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Viandesetufs_10.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Fruitslgumesetherbesaromatiques_11.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - visible with data', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Multiproduit_12.set('fieldLabels', {'fid': 'hidden field', 'N° Carte': 'hidden field', 'Nom de la structure :': 'header label - visible with data', 'Commune où se situe le lieu de vente directe :': 'header label - visible with data', 'Code postal :': 'header label - visible with data', 'N° rue / nom de rue :': 'header label - visible with data', 'E-mail :': 'header label - visible with data', 'Numéro de téléphone :': 'header label - visible with data', 'Site internet :': 'header label - visible with data', 'Page Facebook :': 'header label - visible with data', 'Horaires d\'accueil :': 'header label - visible with data', 'Autre(s) lieu(x) de vente des produits (marchés, distributeurs, magasins ...) :': 'header label - visible with data', 'Type de production :': 'header label - visible with data', 'Produits à la vente :': 'header label - visible with data', 'Précisions': 'header label - visible with data', 'AOP (Appellation d\'origine protégée)': 'header label - visible with data', 'AB (Agriculture Biologique)': 'header label - visible with data', 'IGP (Indication Géographique Protégée)': 'header label - visible with data', 'Label rouge': 'header label - always visible', 'STG (Spécialité Traditionnelle Garantie)': 'header label - visible with data', 'HVE (Haute Valeur Environnementale)': 'header label - visible with data', 'Autres labels et précisions :': 'header label - visible with data', 'Gp_prod': 'hidden field', 'longitude': 'hidden field', 'latitude': 'hidden field', 'result_score': 'hidden field', 'result_score_next': 'hidden field', 'result_label': 'hidden field', 'result_type': 'hidden field', 'result_id': 'hidden field', 'result_housenumber': 'hidden field', 'result_name': 'hidden field', 'result_street': 'hidden field', 'result_postcode': 'hidden field', 'result_city': 'hidden field', 'result_context': 'hidden field', 'result_citycode': 'hidden field', 'result_oldcitycode': 'hidden field', 'result_oldcity': 'hidden field', 'result_district': 'hidden field', 'result_status': 'hidden field', });
lyr_Marchs_13.set('fieldLabels', {'fid': 'hidden field', 'Adresse': 'header label - visible with data', 'Jours d\'ouverture': 'header label - visible with data', 'Horaires': 'header label - visible with data', });
lyr_Marchs_13.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});